config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :projects
  resources :posts
  resources :contacts, only: [:new, :create]
  root 'welcome#index'
  
  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,       :validate => true
  attribute :email,      :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,    :validate => true
  attribute :nickname,   :captcha => true
  
  def headers 
    {
      :subject => "Contact Form",
      :to => "chombot@hotmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = "Cannot send message"
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :find_post, only: [:show, :update, :edit, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @posts = Post.all.order("created_at desc")
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    
    if @post.save
      redirect_to @post, notice: "article saved"
    else
      render 'new', "post could not be saved"
    end
  end
  
  def show
    
  end
  
  def edit
    
  end
  
  
  def update
    if @post.update(post_params)
      redirect_to @post, notice: "all done!"
    else
      render 'edit'
    end
  end
  
  def destroy
    @post.destroy
    redirect_to posts_path
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end
  
  def find_post
    @post = Post.friendly.find(params[:id])
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @projects = Project.all.order("created_at desc")
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: "Great Job Taf, project created!"
    else
      render 'new'
    end
  end
  
  def show
    
  end
  
  def edit
    
  end
  
  def update
    if @project.update(project_params)
      redirect_to @project, notice: "Updated!"
    else
      render 'edit'
    end
  end
  
  def destroy
    @project.destroy
    redirect_to projects_path
  end
  
  private
  
  def find_project
    @project = Project.friendly.find(params[:id])
  end
  def project_params
    params.require(:project).permit(:title, :description, :link)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.order("created_at desc")
    @projects = Project.all.order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true, 
      disable_intended_code_blocks: true, 
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscripit: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Say hello</h1>

<div class="skinny_wrapper wrapper_padding">
  <h1>Thank you for you message!</h1>
  <p>I'll get back to you soon</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Say hello</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= form_for @contact do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true%>
    
    <br>
    
    <%= f.label :email %><br>
    <%= f.email_field :email, required: true%>
    
    <br>
    
    <%= f.label :message %><br>
    <%= f.text_area :message, as: :text %>
    
    <div class="hidden">
      <%= f.label :nickname %><br>
      <%= f.text_field :nickname, hint: 'leave this field blank'%>
    </div>
    
    <%= f.submit 'Send Message', class: "button" %>
    <br>
    
  <% end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>TafDev</title>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  
  <nav class="navbar navbar-dark bg-inverse">
    <%= link_to "TafDev", root_path, class: "name" %>
      
        <%= link_to "Blog", posts_path %>
        <%= link_to "Projects", projects_path %>
        <%= link_to "Contact", new_contact_path %>
        <% if user_signed_in? %>
             <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
         <% end %>
  <!-- Navbar content -->
</nav>

    
      
    </div>
    
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>


<%= yield %>


 <footer id="main_footer">
      <p class="copyright">	&copy;2016 Tafadzwa Chombo</p>
      <nav>
        <a href = "https://github.com/TafDev" target="_blank"><i class="fa fa-github" aria-hidden="true"></i></a>
        <a href = "https://uk.linkedin.com/in/tafadzwa-chombo-4a2a1086" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
      </nav>
      
    </footer>

</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    
    var disqus_config = function () {
        this.page.url = '<%= url_for([@post, {only_path: false}]) %>';
        this.page.identifier = '<%= @post.id %>';
        this.page.title = '<%= @post.title %>';
    };
    
    (function() {  // REQUIRED CONFIGURATION VARIABLE: EDIT THE SHORTNAME BELOW
        var d = document, s = d.createElement('script');
        
        s.src = 'tafdev';  // IMPORTANT: Replace EXAMPLE with your forum shortname!
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
    
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//tafdev.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, "error") %>prevented this post from saving</h2>
      <ul>
        <% @post.errors.full_massages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    
    <br>
    <br>
    
    <%= f.label :content, "write your article here" %><br>
    <%= f.text_area :content %>
    
    <br>
    <br>
    
    <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>

<div class="skinny_wrapper wrapper_padding">

<%= render 'form' %>

</div>

app/views/posts/index.html.erb
<h1 id = "page_title">Stuff i have written</h1>

<div id="posts_wrapper" class="skinny_wrapper">
        <% @posts.each do |post| %>
        <div class = "post">
          <p class="date"><%= post.created_at.strftime("%A, %b, %d") %></p>
          <h2><a href="#"><%= link_to post.title, post %></a></h2>
          <hr>
        </div>
        <% end %>
        
  </div>
  
  <div class="pagination">
    <span class = "previous_page disabled">Previous</span>
    <em class="current">1</em>
    <a rel="next" href="#">Next</a>
  </div>
</div>

app/views/posts/new.html.erb
<h1 id="page_title">New Post</h1>

  <div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</end>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @post.created_at.strftime('%A, %b, %d') %></p>
    <h1><%= @post.title %></h1>
    <hr>
  </header>
  
  <div id="content">
    <%= markdown @post.content %>
  </div>
  
  <hr>
   <% if user_signed_in? %>
     <div id="admin_links">
       <%= link_to "Edit", edit_post_path(@post) %>
       <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure you want to delete?"} %>
     </div>
   <% end %>
  
  <div id="share_box">
    <p></p>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-google-plus"></i></a>
  </div>
  
  <hr>
  
  <%= render 'disqus' %>
</div>

<hr>


<br>
<br>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <h2><%= pluralize(@project.errors.count, "error") %>prevented this project from saving</h2>
      <ul>
        <% @project.errors.full_massages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    
    <br>
    <br>
    
    <%= f.label :description, "write your article here" %><br>
    <%= f.text_area :description %>
    
    <br>
    <br>
    
    <%= f.label :link %><br>
    <%= f.text_field :link %>
    
    <br>
    <br>
    
    <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Edit Project</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id = "page_title">Stuff i have built</h1>

<div id="posts_wrapper" class="skinny_wrapper">
        <% @projects.each do |project| %>
        <div class = "post">
          <p class="date"><%= project.created_at.strftime("%A, %b, %d") %></p>
          <h2><a href="#"><%= link_to project.title, project %></a></h2>
          <hr>
        </div>
        <% end %>
        
  </div>

app/views/projects/new.html.erb
<h1 id="page_title">New Project</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="project_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @project.created_at.strftime('%A, %b, %d') %></p>
    <h1><%= @project.title %></h1>
    <hr>
  </header>
  
  <div id="content">
    <%= markdown @project.description %>
    <hr>
    <a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>
  </div>
  <% if user_signed_in? %>
     <div id="admin_links">
       <%= link_to "Edit", edit_project_path(@project) %>
       <%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure you want to delete?"} %>
     </div>
   <% end %>
</div>

app/views/welcome/index.html.erb
    
    <div class="container">
      <div class="col-md-4">
        <h2>About</h2>
        <hr>
        <p> lorem ipsum todor le value pon sincatir. lorem ipsum todor le value pon sincatir. </p>
        <p> lorem ipsum todor le value pon <a href = "#">sincatir </a>. lorem ipsum todor le value pon sincatir. </p>
        <p> lorem ipsum todor le value pon sincatir.</p>
      </div>
    </div>
      